---
- name: setup group
  group: name={{monasca_group}} system=yes

- name: Setup user
  user: name={{persister_user}} system=yes group={{monasca_group}}

- name: create log_dir
  file: path={{monasca_log_dir}} state=directory owner=root group={{monasca_group}} mode=775

- name: create conf_dir
  file: path={{monasca_conf_dir}} state=directory owner=root group={{monasca_group}} mode=775

- include: java.yml
  when: monasca_persister_java

- include: python.yml
  when: not monasca_persister_java
